version: '3.8'

services:
  mysql:
    image: mysql:8.0.43
    container_name: vbs-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    restart: always

  app:
    build: .

    container_name: virtual-banking-system

    depends_on:
      - mysql

    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    restart: always

volumes:
  mysql-data: